export type Group = "momentum" | "technical" | "fundamental";

export const GROUP_LABELS: Record<Group, string> = {
  momentum: "Momentum staples",
  technical: "Technical",
  fundamental: "Fundamental",
};

export const GROUP_ORDER: Group[] = ["momentum", "technical", "fundamental"];

/** One-line explainer per column/filter key, shown as a hover tooltip. */
export const FIELD_INFO: Record<string, string> = {
  symbol: "NSE trading symbol.",
  exchange: "Listing exchange (NSE only for now).",
  name: "Company name.",
  current_price: "Most recent close price.",
  current_volume: "Most recent day's traded volume.",
  market_cap: "Free-float market capitalization.",
  all_time_high: "Highest price ever recorded for this stock.",
  week_52_high: "Highest price recorded in the trailing 52 weeks.",
  weekly_close: "Close price of the most recent completed week.",
  weekly_volume: "Total traded volume for the most recent completed week.",
  weekly_pct_change: "Percent change vs. the prior week's close.",
  breakout_count: "How many distinct breakout events (pullback, base, re-break) this stock has had under the selected basis.",
  breakout_week: "The week this stock's most recent breakout occurred.",
  breakout_level: "The prior high price that was broken in the most recent breakout.",
  consolidation_weeks: "Weeks spent basing immediately before the most recent breakout.",
  consolidation_range_pct: "Tightness of the base before breakout: (highest high - lowest low) / breakout level.",
  extension_pct: "How far the current price has run beyond the breakout level.",
  breakout_age_weeks: "Weeks elapsed since the most recent breakout.",
  avg_weekly_volume: "Trailing 12-week average weekly volume (liquidity floor).",
  breakout_volume_ratio: "Breakout week's volume divided by the trailing average volume before it. Course rule: should be at least 1.5x.",
  cap_category: "Large/Mid/Small classification by market-cap rank (SEBI convention: top 100 = Large, next 150 = Mid, rest = Small).",
  weeks_of_history: "Number of weekly price bars available for this stock.",
  stock_age: "Time since this stock's earliest available price data (used as a listing-date proxy). Course rule: prefer stocks listed 10 weeks to 15 years ago (the 'IPO base' / 'New India' preference).",
  ema_21d: "21-day exponential moving average of daily close (~3 weeks).",
  ema_50d: "50-day exponential moving average of daily close (~7 weeks).",
  ema_200d: "200-day exponential moving average of daily close (~28 weeks). Course rule: avoid buying below this line.",
  resistance: "Only applies to the 52-Week High view. 'Resistance' means this stock's all-time high is still above its current price -- i.e. there's a higher historical high still overhead that could act as a supply zone.",
  volume_dry_up: "Yes if volume contracted right before the breakout: average volume in the 3 weeks before breakout was under 70% of the trailing 10-week average. A 'volatility contraction' precursor pattern from the course.",
  ema_trend: "Price vs. 21D / 50D / 200D EMAs. Green dot = above, grey = below. Three green dots = full uptrend stack.",
  ema_10w: "10-week EMA of weekly closes. Course sell rule: exit when the weekly close falls below this line.",
  sector: "Company sector (from Yahoo Finance). Informational only -- not a course screening criterion.",
  industry: "Company industry (from Yahoo Finance). Informational only.",
  revenue_growth: "Year-over-year quarterly revenue growth (from Yahoo Finance). Informational only.",
  earnings_growth: "Year-over-year quarterly earnings growth (from Yahoo Finance). Informational only.",
  flags: "Course signals: blue chart-arrow = new ATH this week (primary buy signal); trap = consecutive ~5% up-weeks on negligible volume (avoid); exit = weekly close below 10W EMA; pyramid = a 4+ week box broke out this week (add to winners).",
  score: "Setup quality score out of 8: tight base (<15% range), base length ≥5 wks, fresh breakout (≤4 wks), strong volume (≥2×), vol dry-up, low extension (≤10%), above 200D EMA, above 10W EMA. Hover a score to see which criteria pass.",
  new_high_toggle: "Show only stocks that printed a brand-new high (ATH or 52-week, depending on the selected basis) this calendar week.",
  market_cap_filter: "Course preset: minimum ₹1,000 Cr (risk-takers may go to ₹500 Cr, but never below), upper band ₹50,000 Cr for typical picks.",
  volume_filter: "Liquidity/volume thresholds for the breakout candidate.",
  price_filter: "Filter by current share price.",
  pct_from_high_filter: "How close the current price is to the relevant high (ATH or 52W).",
  extension_filter: "Course rule: don't chase a breakout that's already extended more than ~20% past its breakout level.",
  breakout_age_filter: "Caps how many weeks old the most recent breakout can be -- keeps results to fresh setups.",
  liquidity_filter: "Course preset: breakout volume should be at least 1.5x the trailing average (avoid illiquid 'circuit stock' traps).",
  consolidation_filter: "Course rule: a valid base should run at least ~4-5 weeks and stay reasonably tight.",
  stock_age_filter: "Course preset: 10 weeks to 15 years since listing (the 'IPO base' / 'New India' preference window).",
  exchange_filter: "NSE only (BSE not yet supported).",
  cap_category_filter: "Filter to a single market-cap tier.",
};

export const COLUMN_GROUPS: Record<string, Group> = {
  symbol: "fundamental",
  exchange: "fundamental",
  name: "fundamental",
  cap_category: "fundamental",
  weeks_of_history: "fundamental",
  current_price: "technical",
  current_volume: "technical",
  market_cap: "momentum",
  all_time_high: "technical",
  week_52_high: "technical",
  weekly_close: "technical",
  weekly_volume: "technical",
  weekly_pct_change: "technical",
  ema_21d: "technical",
  ema_50d: "technical",
  ema_200d: "technical",
  avg_weekly_volume: "technical",
  breakout_count: "momentum",
  breakout_week: "momentum",
  breakout_level: "momentum",
  consolidation_weeks: "momentum",
  consolidation_range_pct: "momentum",
  extension_pct: "momentum",
  breakout_age_weeks: "momentum",
  breakout_volume_ratio: "momentum",
  volume_dry_up: "momentum",
  stock_age: "momentum",
  score: "momentum",
  ema_trend: "technical",
  ema_10w: "technical",
  flags: "momentum",
  sector: "fundamental",
  industry: "fundamental",
  revenue_growth: "fundamental",
  earnings_growth: "fundamental",
};

export const FILTER_GROUPS: Record<string, Group> = {
  market_cap: "momentum",
  resistance: "momentum",
  liquidity: "momentum",
  consolidation: "momentum",
  extension: "momentum",
  breakout_age: "momentum",
  pct_from_high: "momentum",
  stock_age: "momentum",
  volume: "technical",
  price: "technical",
  exchange: "fundamental",
  cap_category: "fundamental",
};
